% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Nov-2018 16:50:28
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
                                                  

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [28.583183278987455 97.387491151588478 132.20308440440925];
smiData.RigidTransform(1).angle = 3.1415926535897931;
smiData.RigidTransform(1).axis = [1 0 0];
smiData.RigidTransform(1).ID = 'B[Link1-3:-:Link2-1]';
smiData.RigidTransform(2).translation = ...
  [28.583183278987477 97.387491151588478 130.79731822722405];
smiData.RigidTransform(2).angle = 3.1415926535897918;
smiData.RigidTransform(2).axis = [1 1.5195720360762223E-31 2.4403057145970495E-16 ...
                                  ];
smiData.RigidTransform(2).ID = 'F[Link1-3:-:Link2-1]';
smiData.RigidTransform(3).translation = ...
  [-5.6209218265734391 274.93687443273274 223.43558885187417];
smiData.RigidTransform(3).angle = 2.0943951023931957;
smiData.RigidTransform(3).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962562];
smiData.RigidTransform(3).ID = 'B[Base-1:-:Link1-3]';
smiData.RigidTransform(4).translation = ...
  [28.565183285787413 42.227491159388478 104.38508441440922];
smiData.RigidTransform(4).angle = 2.0943951023931953;
smiData.RigidTransform(4).axis = [0.57735026918962584 -0.57735026918962562 ...
                                  0.577350269189626];
smiData.RigidTransform(4).ID = 'F[Base-1:-:Link1-3]';
smiData.RigidTransform(5).translation = ...
  [169.45895922620957 263.30910321625191 127.57108437701031];
smiData.RigidTransform(5).angle = 1.277058133722624E-15;
smiData.RigidTransform(5).axis = [-0.73895584391332936 -0.67375385768568263 ...
                                  3.17907244436383E-16];
smiData.RigidTransform(5).ID = 'B[Link2-1:-:Link3-1]';
smiData.RigidTransform(6).translation = ...
  [174.64661972258807 258.76108915682624 127.57108437700917];
smiData.RigidTransform(6).angle = 1.5752358999046826E-15;
smiData.RigidTransform(6).axis = [-0.068932278806863048 0.99762134146102388 ...
                                  -5.4163157276125016E-17];
smiData.RigidTransform(6).ID = 'F[Link2-1:-:Link3-1]';
smiData.RigidTransform(7).translation = ...
  [-5.6209218265734391 246.93687442573273 223.43558885187417];
smiData.RigidTransform(7).angle = 1.5707963267948961;
smiData.RigidTransform(7).axis = [-1 0 0];
smiData.RigidTransform(7).ID = 'AssemblyGround[Base-1:MX-64T-1]';
smiData.RigidTransform(8).translation = ...
  [-5.6209218265734391 254.93687443273271 223.43558885187417];
smiData.RigidTransform(8).angle = 0;
smiData.RigidTransform(8).axis = [0 0 0];
smiData.RigidTransform(8).ID = 'AssemblyGround[Base-1:Base-1]';
smiData.RigidTransform(9).translation = ...
  [7.5511442995132709 -194.2673478928719 -43.035588851874138];
smiData.RigidTransform(9).angle = 0;
smiData.RigidTransform(9).axis = [0 0 0];
smiData.RigidTransform(9).ID = 'RootGround[Base-1]';
smiData.Solid = struct;
smiData.Solid(1).mass = 0.228;
smiData.Solid(1).CoM = [28.582957740285682 74.651340671551026 104.7787142982849 ...
                        ];
smiData.Solid(1).MoI = [169.32731336237669 104.36197449507746 149.82146080994016 ...
                        ];
smiData.Solid(1).PoI = [-2.934033300852648 0.0046662964490011734 -0.031812697060705192 ...
                        ];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'Link1*:*Default';
smiData.Solid(2).mass = 0.126;
smiData.Solid(2).CoM = [2.0020780403534165E-5 -15.204445238597625 0.4522731114713906 ...
                        ];
smiData.Solid(2).MoI = [51.921756876046572 29.517310753585011 43.332851083946437 ...
                        ];
smiData.Solid(2).PoI = [-1.5325719334224883 6.2827043307171043E-7 -7.3479582330330162E-5 ...
                        ];
smiData.Solid(2).color = [0.75294117647058822 0.75294117647058822 1];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'MX-64T*:*Default';
smiData.Solid(3).mass = 0.42628184131549768;
smiData.Solid(3).CoM = [0 -35.286263565794044 0];
smiData.Solid(3).MoI = [2483.8708366853707 2557.0476972167057 2483.8708366853703 ...
                        ];
smiData.Solid(3).PoI = [0 0 0];
smiData.Solid(3).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'Base*:*Default';
smiData.Solid(4).mass = 0.228;
smiData.Solid(4).CoM = [138.43589754801727 228.18151143509283 104.49362752930682 ...
                        ];
smiData.Solid(4).MoI = [493.28655581778679 397.38776500016456 810.24270690681294 ...
                        ];
smiData.Solid(4).PoI = [-1.7456456404431979 -1.4854591103638486 -381.74683501062805 ...
                        ];
smiData.Solid(4).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Link2*:*Default';
smiData.Solid(5).mass = 0.1164443197731465;
smiData.Solid(5).CoM = [280.83251718058955 317.9351094376828 105.81697025643109 ...
                        ];
smiData.Solid(5).MoI = [85.691440998056223 157.11091004892626 153.72103499426657 ...
                        ];
smiData.Solid(5).PoI = [-0.26828727289027521 -0.422631769956474 -51.838893139160348 ...
                        ];
smiData.Solid(5).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'Link3*:*Default';
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = -40.411898544838657;
smiData.RevoluteJoint(1).ID = '[Link1-3:-:Link2-1]';
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = -89.928089125088079;
smiData.RevoluteJoint(2).ID = '[Base-1:-:Link1-3]';
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = 20.656865157727466;
smiData.RevoluteJoint(3).ID = '[Link2-1:-:Link3-1]';

